import turtle

kaks = turtle.Turtle()
kaks.penup()
kaks.goto(150,150)
kaks.pendown()
for _ in range(4):
    kaks.shape('circle')
    color = ('blue')
    kaks.color(color)
    kaks.forward(100)
    kaks.left(90)
kaks.penup()
kaks.goto(-150,150)
kaks.pendown()
for _ in range(4):
    kaks.shape('turtle')
    color = ('teal')
    kaks.color(color)
    kaks.left(90)
    kaks.forward(100)
kaks.penup()
kaks.goto(-150,-150)
kaks.pendown()
for _ in range(4):
    kaks.shape('circle')
    color = ('yellow')
    kaks.color(color)
    kaks.forward(-100)
    kaks.right(90)
kaks.penup()
kaks.goto(150,-150)
kaks.pendown()
for _ in range(4):
    kaks.shape('turtle')
    color = ('violet')
    kaks.color(color)
    kaks.right(90)
    kaks.forward(-100)
kaks.penup()
kaks.goto(70,130)
kaks.pendown()
for _ in range(4):
    kaks.shape('triangle')
    color = ('pink')
    kaks.color(color)
    kaks.right(90)
    kaks.forward(150)